#!/bin/sh

#
# Install
#
cd `dirname $0`
. ./Configuration

if [ ! -d ${EMAGELOAD_OUTPUTDIR} ]
then
    mkdir -p ${EMAGELOAD_OUTPUTDIR}
fi

if [ ! -d ${EMAGELOAD_LOGDIR} ]
then
    mkdir -p ${EMAGELOAD_LOGDIR}
fi

if [ ! -d ${EMAGELOAD_RPTDIR} ]
then
    mkdir -p ${EMAGELOAD_RPTDIR}
fi
